-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgT9fuFPFfeVP/EJdi
ZbmUaCisdlMrBYOawDhqFAgkCWygCgYIKoZIzj0DAQehRANCAASSuMke6K1LiCaK
cmkf2f950RfZ3qq0/iLS+JEXHdXiBhAnYHolT0qWQJ3XgzQWJEMIj1wGUNirkZxM
+gcbHs7v
-----END PRIVATE KEY-----